// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2515.ENIGMA;

import org.usfirst.frc2515.ENIGMA.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc2515.ENIGMA.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton buttonToggleManualDrive;
    public JoystickButton liftUpButton;
    public JoystickButton liftDownButton;
    public JoystickButton resetLiftEncoderButton;
    public JoystickButton extendArmButton;
    public JoystickButton liftToHatchLevel1Button;
    public JoystickButton liftToCargoLevel1Button;
    public JoystickButton stopLiftMotorsButton;
    public JoystickButton startCargoIntakeButton;
    public JoystickButton ejectCargoButton;
    public Joystick driverStick;
    public JoystickButton elevateButton;
    public JoystickButton retractFront;
    public JoystickButton retractRear;
    public Joystick copilotStick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        copilotStick = new Joystick(1);
        
        retractRear = new JoystickButton(copilotStick, 2);
        retractRear.whileHeld(new retractRearElevator());
        retractFront = new JoystickButton(copilotStick, 3);
        retractFront.whenPressed(new retractFrontElevator());
        elevateButton = new JoystickButton(copilotStick, 4);
        elevateButton.whenPressed(new elevateChassis());
        driverStick = new Joystick(0);
        
        ejectCargoButton = new JoystickButton(driverStick, 1);
        ejectCargoButton.whenPressed(new releaseCargo());
        startCargoIntakeButton = new JoystickButton(driverStick, 2);
        startCargoIntakeButton.whenPressed(new grabCargo(0));
        stopLiftMotorsButton = new JoystickButton(driverStick, 11);
        stopLiftMotorsButton.whenPressed(new stopLift());
        liftToCargoLevel1Button = new JoystickButton(driverStick, 10);
        liftToCargoLevel1Button.whenPressed(new liftAuto(0));
        liftToHatchLevel1Button = new JoystickButton(driverStick, 8);
        liftToHatchLevel1Button.whenPressed(new liftAuto(0));
        extendArmButton = new JoystickButton(driverStick, 7);
        extendArmButton.whenPressed(new toggleArmExtension());
        resetLiftEncoderButton = new JoystickButton(driverStick, 6);
        resetLiftEncoderButton.whenPressed(new resetLiftEncoder());
        liftDownButton = new JoystickButton(driverStick, 4);
        liftDownButton.whileHeld(new liftManual(-25));
        liftUpButton = new JoystickButton(driverStick, 3);
        liftUpButton.whileHeld(new liftManual(25));
        buttonToggleManualDrive = new JoystickButton(driverStick, 5);
        buttonToggleManualDrive.whenPressed(new toggleManualDrive());


        // SmartDashboard Buttons
        SmartDashboard.putData("emergencyReset", new emergencyReset());
        SmartDashboard.putData("grabCargo: bottom", new grabCargo(0));
        SmartDashboard.putData("grabHatchPanel", new grabHatchPanel());
        SmartDashboard.putData("releaseCargo", new releaseCargo());
        SmartDashboard.putData("releaseHatchPanel", new releaseHatchPanel());
        SmartDashboard.putData("toggleManualDrive", new toggleManualDrive());
        SmartDashboard.putData("elevateChassis", new elevateChassis());
        SmartDashboard.putData("retractFrontElevator", new retractFrontElevator());
        SmartDashboard.putData("retractRearElevator", new retractRearElevator());
        SmartDashboard.putData("stopLift", new stopLift());
        SmartDashboard.putData("liftAuto: top", new liftAuto(0));
        SmartDashboard.putData("liftAuto: cargoLevel2", new liftAuto(0));
        SmartDashboard.putData("liftAuto: hatchLevel2", new liftAuto(0));
        SmartDashboard.putData("liftAuto: cargoLevel1", new liftAuto(0));
        SmartDashboard.putData("liftAuto: hatchLevel1", new liftAuto(0));
        SmartDashboard.putData("liftAuto: bottom", new liftAuto(0));
        SmartDashboard.putData("liftManual: up", new liftManual(25));
        SmartDashboard.putData("liftManual: down", new liftManual(-25));
        SmartDashboard.putData("resetLiftEncoder", new resetLiftEncoder());
        SmartDashboard.putData("toggleArmExtension", new toggleArmExtension());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getdriverStick() {
        return driverStick;
    }

    public Joystick getcopilotStick() {
        return copilotStick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

