// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2515.ENIGMA_V2.subsystems;

import org.usfirst.frc2515.ENIGMA_V2.Robot;
import org.usfirst.frc2515.ENIGMA_V2.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.smartdashboard.*;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class driveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX leftDriveTalon;
    private WPI_TalonSRX rightDriveTalon;
    private DifferentialDrive diffDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private double accelerateMultiplier;

    public driveTrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        leftDriveTalon = new WPI_TalonSRX(1);
        
        
        
        rightDriveTalon = new WPI_TalonSRX(2);
        
        
        
        diffDrive = new DifferentialDrive(leftDriveTalon, rightDriveTalon);
        addChild("diffDrive",diffDrive);
        diffDrive.setSafetyEnabled(true);
        diffDrive.setExpiration(0.1);
        diffDrive.setMaxOutput(1.0);

        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        accelerateMultiplier = (Robot.oi.driverStick.getRawAxis(3) + 3) * .25;
        SmartDashboard.putNumber("Accelerate Multiplier", accelerateMultiplier);
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void operatorDrive() {
        double forward = -1 * Robot.oi.driverStick.getRawAxis(1); /* positive is forward */
        double turn = +1 * Robot.oi.driverStick.getRawAxis(2); /* positive is right */
        /* deadband gamepad 15% */
        if (Math.abs(forward) < 0.15) {
            forward = 0;
        }
        if (Math.abs(turn) < 0.15) {
            turn = 0;
        }
        if (Robot.autoSteerEngaged){
            turn = Robot.sensors.followLine();
        }
        diffDrive.arcadeDrive(forward * accelerateMultiplier, turn * accelerateMultiplier);
    }
    public void driveReverse(){
        diffDrive.arcadeDrive(-.5, 0);
    }
    public void stop(){
        diffDrive.stopMotor();
    }
}

